version: "3.7"
services:
  db:
    image: "mysql:8"
    container_name: itsgrowingapp_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: itsgrowingapp_db
      MYSQL_ROOT_PASSWORD: 1t5gr0w1ng4pp-b6
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - itsgrowingapp_net
    restart: always
    security_opt:
      - seccomp:unconfined
  adminer:
    image: "adminer:latest"
    container_name: itsgrowingapp_adminer
    ports:
      - "8888:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - itsgrowingapp_net
    depends_on:
      - db
    restart: on-failure
networks:
  itsgrowingapp_net:
    driver: bridge
volumes:
  dbdata:
    driver: local